# General
name: Veggie Spotter
tagline: Find vegetarian places near you!

# Jekyll
exclude: ['Rakefile']
markdown: redcarpet

# App Store
appstore_url: https://itunes.apple.com/app/veggie-spotter/id1260051076
appstore: <a href="https://itunes.apple.com/app/veggie-spotter/id1260051076" class="app-store" rel="external nofollow"><img src="/assets/app-store.svg" alt="Download on the App Store"></a>
appstore_white: <a href="https://itunes.apple.com/app/veggie-spotter/id1260051076" class="app-store" rel="external nofollow"><img src="/assets/app-store-white.svg" alt="Download on the App Store"></a>

# Screenshots
screenshots:
- screenshot01
- screenshot02
- screenshot03
- screenshot04

# Company Info
company: José Tapadas Alves
company_website: http://josetapadas.github.io

# Emails
email_press: jose.tapadas@gmail.com
email_contact: jose.tapadas@gmail.com
email_support: jose.tapadas@gmail.com
